-- Veyra Supabase bootstrap schema
-- Run this in Supabase SQL Editor before setting SUPABASE_URL and SUPABASE_SECRET_KEY.

create table if not exists public.app_state (
  id text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.app_state enable row level security;

-- The backend uses a Supabase secret key and talks to this table through the REST Data API.
-- No browser policy is granted intentionally; do not expose the secret key to the client.

create index if not exists app_state_updated_at_idx on public.app_state (updated_at desc);

-- Relational tables for the next migration step. The current MVP stores the complete
-- snapshot in app_state so local JSON and cloud persistence share the same contract.
create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  kind text not null default 'household',
  created_at timestamptz not null default now()
);

create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(),
  group_id uuid references public.groups(id) on delete cascade,
  registration text not null unique,
  name text not null,
  powertrain text,
  capabilities jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.position_events (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid references public.vehicles(id) on delete cascade,
  event_id text not null unique,
  device_time timestamptz,
  received_at timestamptz not null default now(),
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m double precision,
  speed_kmh double precision,
  ignition boolean,
  quality text not null default 'measured',
  raw_payload jsonb
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  group_id uuid references public.groups(id) on delete set null,
  actor text not null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.groups enable row level security;
alter table public.vehicles enable row level security;
alter table public.position_events enable row level security;
alter table public.audit_logs enable row level security;

-- Add authenticated-user policies once Supabase Auth and group membership tables are enabled.
-- The server-side secret key bypasses RLS; application authorization remains enforced in server.js.
