package com.veyra.tracker;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.text.InputFilter;
import android.text.InputType;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    static final String API = "https://verya-r4wm.onrender.com";
    static final String PREFS = "veyra_tracker";
    private final ExecutorService io = Executors.newSingleThreadExecutor();
    private EditText phone, otp; private TextView status; private Button start, camera, microphone; private String pendingPhoneValue, pendingOtpCode; private boolean verifyInProgress, activationDialogShown;
    private SharedPreferences prefs;

    @Override public void onCreate(Bundle state) { super.onCreate(state); prefs = getSharedPreferences(PREFS, MODE_PRIVATE); buildUi(); if (paired()) { start.setEnabled(prefs.getBoolean("tracking_approved", false)); startActivationListener(); } }
    @Override protected void onResume() { super.onResume(); if (paired()) checkActivationRequest(); }
    private void buildUi() {
        LinearLayout root = new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(32, 48, 32, 32);
        TextView title = new TextView(this); title.setText("Veyra Tracker\nMobile GPS device"); title.setTextSize(24); root.addView(title);
        TextView info = new TextView(this); info.setText("Pair this phone with your Veyra account. Location tracking starts after Notifications and Location ‘Allow all the time’ permissions are granted. Camera and microphone are temporarily disabled."); root.addView(info);
        phone = field("10-digit mobile number"); phone.setInputType(InputType.TYPE_CLASS_PHONE); phone.setFilters(new InputFilter[]{new InputFilter.LengthFilter(10)}); root.addView(phone);
        Button request = button("Send OTP"); root.addView(request); request.setOnClickListener(v -> requestOtp());
        otp = field("OTP code"); otp.setInputType(2); root.addView(otp);
        Button verify = button("Verify and pair"); root.addView(verify); verify.setOnClickListener(v -> verifyPairing());
        start = button("Start background tracking"); root.addView(start); start.setEnabled(false); start.setOnClickListener(v -> startTracking());
        camera = button("Vehicle camera (temporarily disabled)"); root.addView(camera); camera.setVisibility(View.GONE); camera.setOnClickListener(v -> enableCamera());
        microphone = button("Microphone (temporarily disabled)"); root.addView(microphone); microphone.setVisibility(View.GONE); microphone.setOnClickListener(v -> enableMicrophone());
        status = new TextView(this); status.setText("Not paired"); root.addView(status); setContentView(root);
    }
    private EditText field(String hint) { EditText e = new EditText(this); e.setHint(hint); e.setPadding(0, 24, 0, 12); return e; }
    private Button button(String label) { Button b = new Button(this); b.setText(label); return b; }
    private boolean paired() { return prefs.contains("device_token") && prefs.contains("device_link_id"); }
    private String phoneValue() { String digits = phone.getText().toString().replaceAll("\\D", ""); if (digits.length() != 10) { status.setText("Enter exactly 10 digits."); return null; } return "+91" + digits; }
    private void requestOtp() { final String value = phoneValue(); if (value == null) return; status.setText("Sending OTP…"); try { JSONObject body = new JSONObject(); body.put("phone", value); post("/api/phone/request", body, result -> status.setText(result.optString("demoCode", "OTP sent. Check your phone."))); } catch (Exception e) { status.setText(e.getMessage()); } }
    private void verifyPairing() { if (verifyInProgress) return; final String value = phoneValue(); if (value == null) return; pendingPhoneValue = value; pendingOtpCode = otp.getText().toString().trim(); continuePermissionGate(); }
    private boolean mediaPermissionsReady() { return Build.VERSION.SDK_INT < 23 || (checkSelfPermission(Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED && checkSelfPermission(Manifest.permission.RECORD_AUDIO) == PackageManager.PERMISSION_GRANTED); }
    private boolean notificationPermissionReady() { return Build.VERSION.SDK_INT < 33 || checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) == PackageManager.PERMISSION_GRANTED; }
    private boolean foregroundLocationReady() { return checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED; }
    private boolean backgroundLocationReady() { return Build.VERSION.SDK_INT < 29 || checkSelfPermission(Manifest.permission.ACCESS_BACKGROUND_LOCATION) == PackageManager.PERMISSION_GRANTED; }
    private void continuePermissionGate() { if (!notificationPermissionReady()) { status.setText("Allow notifications so tracking stays visible."); if (Build.VERSION.SDK_INT >= 33) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS}, 28); return; } if (!foregroundLocationReady()) { status.setText("Allow location, then choose all-time/background access."); requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION}, 26); return; } if (!backgroundLocationReady()) { status.setText("Choose Allow all the time for location to continue."); if (Build.VERSION.SDK_INT >= 29) requestPermissions(new String[]{Manifest.permission.ACCESS_BACKGROUND_LOCATION}, 27); return; } completeVerifyPairing(); }
    private void completeVerifyPairing() { if (verifyInProgress || pendingPhoneValue == null) return; verifyInProgress = true; status.setText("Permissions allowed. Verifying device…"); try { JSONObject body = new JSONObject(); body.put("phone", pendingPhoneValue); body.put("code", pendingOtpCode); post("/api/phone/verify", body, result -> { verifyInProgress = false; prefs.edit().putString("device_token", result.getString("deviceToken")).putString("device_link_id", result.getString("deviceLinkId")).putBoolean("tracking_approved", false).putBoolean("camera_permission_ready", false).putBoolean("mic_permission_ready", false).apply(); runOnUiThread(() -> { start.setEnabled(false); status.setText("Paired. Waiting for the admin to request tracking."); startActivationListener(); checkActivationRequest(); }); }); } catch (Exception e) { verifyInProgress = false; status.setText(e.getMessage()); } }
    private void requestLocationPermissions() { if (Build.VERSION.SDK_INT >= 33 && checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS}, 20); if (checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION}, 21); else if (Build.VERSION.SDK_INT >= 29 && checkSelfPermission(Manifest.permission.ACCESS_BACKGROUND_LOCATION) != PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.ACCESS_BACKGROUND_LOCATION}, 22); }
    private boolean locationReady() { return checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED || checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED; }
    private void startTracking() { if (!prefs.getBoolean("tracking_approved", false)) { status.setText("Waiting for your confirmation and admin activation request."); checkActivationRequest(); return; } if (!locationReady()) { requestLocationPermissions(); status.setText("Allow location permission, then tap Start again."); return; } if (Build.VERSION.SDK_INT >= 29 && checkSelfPermission(Manifest.permission.ACCESS_BACKGROUND_LOCATION) != PackageManager.PERMISSION_GRANTED) { requestPermissions(new String[]{Manifest.permission.ACCESS_BACKGROUND_LOCATION}, 22); status.setText("Allow background location, then tap Start again."); return; } Intent i = new Intent(this, LocationService.class); if (Build.VERSION.SDK_INT >= 26) startForegroundService(i); else startService(i); status.setText("Tracking active after consent. Keep the Veyra notification enabled."); moveTaskToBack(true); }
    private void startActivationListener() { Intent i = new Intent(this, LocationService.class); if (Build.VERSION.SDK_INT >= 26) startForegroundService(i); else startService(i); }
    private void checkActivationRequest() { io.execute(() -> { try { URL url = new URL(API + "/api/device/activation?deviceLinkId=" + java.net.URLEncoder.encode(prefs.getString("device_link_id", ""), "UTF-8")); HttpURLConnection c = (HttpURLConnection)url.openConnection(); c.setRequestMethod("GET"); c.setRequestProperty("X-Device-Token", prefs.getString("device_token", "")); int code = c.getResponseCode(); BufferedReader r = new BufferedReader(new InputStreamReader(code < 400 ? c.getInputStream() : c.getErrorStream())); StringBuilder text = new StringBuilder(); String line; while ((line = r.readLine()) != null) text.append(line); if (code >= 400) throw new Exception(new JSONObject(text.toString()).optString("error", "Activation check failed")); JSONObject result = new JSONObject(text.toString()); runOnUiThread(() -> handleActivationState(result)); } catch (Exception e) { runOnUiThread(() -> status.setText("Waiting for network to check tracking request.")); } }); }
    private void handleActivationState(JSONObject result) { try { String state = result.optString("activationStatus", "idle"); if ("approved".equals(state)) { prefs.edit().putBoolean("tracking_approved", true).apply(); start.setEnabled(true); status.setText("Tracking approved. Starting location sharing…"); startTracking(); return; } prefs.edit().putBoolean("tracking_approved", false).apply(); start.setEnabled(false); if ("pending".equals(state) && !activationDialogShown) { activationDialogShown = true; new AlertDialog.Builder(this).setTitle("Tracking request").setMessage("The Veyra admin wants to start live vehicle tracking" + (result.optString("vehicleName", "").isEmpty() ? "." : " for " + result.optString("vehicleName") + ".") + "\n\nYour location will be shared only after you confirm.").setNegativeButton("Reject", (dialog, which) -> respondToActivation(false)).setPositiveButton("Confirm & start", (dialog, which) -> respondToActivation(true)).setOnDismissListener(dialog -> activationDialogShown = false).show(); } else if ("rejected".equals(state)) status.setText("Tracking request was rejected. Ask the admin to send it again."); else status.setText("Paired. Waiting for the admin to request tracking."); } catch (Exception e) { status.setText(e.getMessage()); } }
    private void respondToActivation(boolean approve) { status.setText(approve ? "Confirming tracking permission…" : "Rejecting tracking request…"); try { JSONObject body = new JSONObject(); body.put("deviceLinkId", prefs.getString("device_link_id", "")); body.put("decision", approve ? "approve" : "reject"); postDevice("/api/device/activation", body, result -> { boolean accepted = "approved".equals(result.optString("activationStatus")); prefs.edit().putBoolean("tracking_approved", accepted).apply(); runOnUiThread(() -> { start.setEnabled(accepted); if (accepted) startTracking(); else status.setText("Tracking request rejected. Location sharing is off."); }); }); } catch (Exception e) { status.setText(e.getMessage()); } }
    private void enableCamera() { if (Build.VERSION.SDK_INT >= 23 && checkSelfPermission(Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) { requestPermissions(new String[]{Manifest.permission.CAMERA}, 23); status.setText("Allow camera permission. The admin Camera button controls the camera."); return; } prefs.edit().putBoolean("camera_permission_ready", true).apply(); status.setText("Camera permission ready. The admin Camera button controls the front or back camera."); }
    private void enableMicrophone() { if (Build.VERSION.SDK_INT >= 23 && checkSelfPermission(Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) { requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO}, 24); status.setText("Allow microphone permission. The admin can then turn Mic on from the dashboard."); return; } prefs.edit().putBoolean("mic_permission_ready", true).apply(); status.setText("Microphone permission ready. The admin Mic button controls listening."); }
    @Override public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] results) { super.onRequestPermissionsResult(requestCode, permissions, results); if (requestCode == 25) { if (mediaPermissionsReady()) continuePermissionGate(); else { verifyInProgress = false; status.setText("Both camera and microphone permissions are required. Verification cancelled."); } } if (requestCode == 28) { if (notificationPermissionReady()) continuePermissionGate(); else { verifyInProgress = false; status.setText("Notification permission is required. Verification cancelled."); } } if (requestCode == 26) { if (foregroundLocationReady()) continuePermissionGate(); else { verifyInProgress = false; status.setText("Location permission is required. Verification cancelled."); } } if (requestCode == 27) { if (backgroundLocationReady()) continuePermissionGate(); else { verifyInProgress = false; status.setText("Choose Allow all the time for location. Verification cancelled."); } } if ((requestCode == 21 || requestCode == 22) && locationReady()) { status.setText("Location allowed. Starting background tracking…"); startTracking(); } if (requestCode == 23 && checkSelfPermission(Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED) enableCamera(); if (requestCode == 24 && checkSelfPermission(Manifest.permission.RECORD_AUDIO) == PackageManager.PERMISSION_GRANTED) enableMicrophone(); }
    private interface Result { void ok(JSONObject value) throws Exception; }
    private void postDevice(String path, JSONObject body, Result callback) { io.execute(() -> { try { HttpURLConnection c = (HttpURLConnection)new URL(API + path).openConnection(); c.setRequestMethod("POST"); c.setRequestProperty("Content-Type", "application/json"); c.setRequestProperty("X-Device-Token", prefs.getString("device_token", "")); c.setDoOutput(true); try (OutputStream out = c.getOutputStream()) { out.write(body.toString().getBytes(StandardCharsets.UTF_8)); } int code = c.getResponseCode(); BufferedReader r = new BufferedReader(new InputStreamReader(code < 400 ? c.getInputStream() : c.getErrorStream())); StringBuilder text = new StringBuilder(); String line; while ((line = r.readLine()) != null) text.append(line); JSONObject result = new JSONObject(text.toString()); if (code >= 400) throw new Exception(result.optString("error", "Request failed")); runOnUiThread(() -> { try { callback.ok(result); } catch (Exception e) { status.setText(e.getMessage()); } }); } catch (Exception e) { runOnUiThread(() -> status.setText(e.getMessage())); } }); }
    private void post(String path, JSONObject body, Result callback) { io.execute(() -> { try { HttpURLConnection c = (HttpURLConnection)new URL(API + path).openConnection(); c.setRequestMethod("POST"); c.setRequestProperty("Content-Type", "application/json"); c.setDoOutput(true); try (OutputStream out = c.getOutputStream()) { out.write(body.toString().getBytes(StandardCharsets.UTF_8)); } int code = c.getResponseCode(); BufferedReader r = new BufferedReader(new InputStreamReader(code < 400 ? c.getInputStream() : c.getErrorStream())); StringBuilder text = new StringBuilder(); String line; while ((line = r.readLine()) != null) text.append(line); JSONObject result = new JSONObject(text.toString()); if (code >= 400) throw new Exception(result.optString("error", "Request failed")); runOnUiThread(() -> { try { callback.ok(result); } catch (Exception e) { status.setText(e.getMessage()); } }); } catch (Exception e) { runOnUiThread(() -> status.setText(e.getMessage())); } }); }
}
